#FROM  alpine:latest
#RUN   apk update && apk add figlet
#ADD   ./message.txt /message.txt
#EXPOSE 80
#ENV   VAR01=abcd
#CMD   echo $VAR01 | figlet




#FROM  openjdk:17-jdk-buster
#ADD ./build/libs/test-0.0.1-SNAPSHOT.jar /backend/app.jar
#ENV DBURL=jdbc:mariadb://192.168.0.114:3306/test
#ENV DBUSER=root
#ENV DBPASSWORD=qwer1234
#CMD java -jar /backend/app.jar

FROM openjdk:17-jdk-buster
EXPOSE 8080
ARG JAR_FILE
ADD ${JAR_FILE} /app.jar
CMD java -jar /app.jar
#ADD ./build/libs/test-0.0.1-SNAPSHOT.jar /backend/app.jar
#ENV DBURL=jdbc:mariadb://192.168.0.114:3306/test
#ENV DBUSER=root
#ENV DBPASSWORD=qwer1234
#CMD java -jar /backend/app.jar

